name: Horusec SAST

on:
  push:
    branches:
      - main  # Troque "main" pelo nome da sua branch principal, se necessário

jobs:
  horusec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Horusec
        run: |
          curl -fsSL https://install.horusec.io | bash
          sudo mv ./horusec /usr/local/bin/horusec

      - name: Run Horusec
        run: |
          horusec start -p . -e "$(cat horusec-config.json)"

      - name: Upload Horusec Results
        uses: actions/upload-artifact@v2
        with:
          name: horusec-results
          path: horusec-output.json
