name: SecurityPipeline

 

on:
  push:
    branches:
      - main  # Substitua pelo nome da sua branch principal

 

jobs:
  horusec-security:
    name: Horusec Security Scan
    runs-on: ubuntu-latest

 

    steps:
      - name: Verificar código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

 

      - name: Instalar Horusec Security
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest

 

      - name: Executar Horusec Security Scan
        run: horusec start -p="./" -e="false"
